// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbqGOm32OqF_xjk8eajr6r8fDKu3c2IEg',
    appId: '1:172658097249:web:098ef59797b6aa62b2be20',
    messagingSenderId: '172658097249',
    projectId: 'weather-b2a00',
    authDomain: 'weather-b2a00.firebaseapp.com',
    storageBucket: 'weather-b2a00.firebasestorage.app',
    measurementId: 'G-V0CQQVTZ2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGdty9gDZmjkZ4KcGtcML6gTISLP5f3SI',
    appId: '1:172658097249:android:fe785f1fbf01058fb2be20',
    messagingSenderId: '172658097249',
    projectId: 'weather-b2a00',
    storageBucket: 'weather-b2a00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOMN2QP2UP_1JS1JslK452hR6GnMElKR0',
    appId: '1:172658097249:ios:a4132c613c38b2d9b2be20',
    messagingSenderId: '172658097249',
    projectId: 'weather-b2a00',
    storageBucket: 'weather-b2a00.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOMN2QP2UP_1JS1JslK452hR6GnMElKR0',
    appId: '1:172658097249:ios:a4132c613c38b2d9b2be20',
    messagingSenderId: '172658097249',
    projectId: 'weather-b2a00',
    storageBucket: 'weather-b2a00.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbqGOm32OqF_xjk8eajr6r8fDKu3c2IEg',
    appId: '1:172658097249:web:4a820afc77c4504fb2be20',
    messagingSenderId: '172658097249',
    projectId: 'weather-b2a00',
    authDomain: 'weather-b2a00.firebaseapp.com',
    storageBucket: 'weather-b2a00.firebasestorage.app',
    measurementId: 'G-B28KGPWXNM',
  );
}
